apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-deployment  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sampleapp
        image: abhin785/sampleapp:${BUILD_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
        env:
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:5000

---

apiVersion: v1
kind: Service
metadata:
  name: sampleapp-service
spec:
  selector:
    app: sampleapp
  ports:
    - protocol: TCP
      port: 9090              
      targetPort: 9090      
  type: LoadBalancer
